ログイン・ログアウト機能、テスト実装
shinonome-inc/backend-final-assignment-Franco-Enzian pull request #2
Opened 2023-09-01 13:45 UTC by 4Franco-star

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-09-02 15:20 UTC, yodapuuu reviewed
良い感じです！

2023-09-02 15:20 UTC, yodapuuu commented on templates/registration/login.html
template以下のファイルですがaccountsとtweetsの二つの統一でお願いします。
accounts/login.htmlみたいな！

2023-09-02 15:20 UTC, yodapuuu commented on accounts/views.py
LogoutViewも作ってください！

2023-09-03 12:51 UTC, 4Franco-star commented on templates/registration/login.html
すみません、実はそのようにしたかったのですが、accounts/login.htmlの状態でランサーバーしログインのURLをクリックすると以下のエラーが出ます。
TemplateDoesNotExist at /accounts/login/
registration/login.html
registrationフォルダを作ってhtmlを入れてみると問題なく動作します。
おそらくデフォルトでregistrationディレクトリを参照するように設定されているのかもしれません。よくある質問集を確認してもそこに記載されている設定はきちんとされていました。どうすればよいでしょうか？

2023-09-04 08:11 UTC, 4Franco-star commented on templates/registration/login.html
解決しました！

2023-09-04 13:54 UTC, yodapuuu commented
1次LGTM

2023-09-05 01:47 UTC, sui-false commented
テストでコンフリクト起きてるので、解消してください

2023-09-05 01:48 UTC, sui-false requested changes
おおむね良いと思います。
軽微な点のみ、修正お願いします。

2023-09-05 01:48 UTC, sui-false commented on accounts/views.py
> +class LogoutView(auth_views.LogoutView):
この書き方ならここにLogoutViewを書く必要がないので、他の書き方を調べてみてください。

2023-09-06 02:33 UTC, sui-false requested changes
１点のみ修正お願いします

2023-09-06 02:33 UTC, sui-false commented on accounts/urls.py
> +    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
今、view.pyにも同様の記述がありますが、ダブってるのでどちらかに絞ってよいと思います。この場合、viewのLoginViewのクラスを使ってなさそうなので、viewの方を消すと良いと思います

2023-09-06 03:29 UTC, sui-false approved these changes

2023-09-06 03:30 UTC, sui-false commented
良いと思います！

2023-09-06 03:30 UTC, merged