ツイート機能実装
shinonome-inc/backend-final-assignment-Franco-Enzian pull request #3
Opened 2023-11-08 10:24 UTC by 4Franco-star

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-11-11 06:45 UTC, nishikou-1216 reviewed
1点だけコメントさせていただきました。

2023-11-11 06:45 UTC, nishikou-1216 commented on templates/tweets/home.html
> +<a href="{% url 'tweets:delete' tweet.pk %}">削除</a>
他のuserが自分のtweetを見ているときは、消去ボタンが表示されないようにしてあげるともっと良くなると思います。

2023-11-11 07:18 UTC, 4Franco-star commented on templates/tweets/home.html
> +<a href="{% url 'tweets:delete' tweet.pk %}">削除</a>
ログイン中のユーザーのtweetにのみ削除ボタンが表示されるよう修正しました！

2023-11-11 10:20 UTC, nishikou-1216 commented
1次レビューLGTM

2023-11-12 16:41 UTC, sui-false requested changes
修正お願いします

2023-11-12 16:41 UTC, sui-false commented on accounts/tests.py
> +class TestTUserProfileView(TestCase):
typoです

2023-11-12 16:41 UTC, sui-false commented on templates/tweets/detail.html
> +<h2>{{ tweet.user }}</h2>
このままだとホームに戻れないので、戻るボタンを作りましょう

2023-11-12 16:41 UTC, sui-false commented on tweets/tests.py
> +        self.assertEqual(Tweet.objects.count(), initial_tweet_count)
これではテストになってません。どのタイミングで何をテストしたいか考えてみましょう。

2023-11-12 16:41 UTC, sui-false commented on tweets/tests.py
> +        self.assertEqual(tweets_count_before, tweets_count_after)
ここも同じです。

2023-11-12 16:41 UTC, sui-false commented on tweets/tests.py
> +        self.assertEqual(tweets_count_before, tweets_count_after)
ここも

2023-11-13 00:29 UTC, 4Franco-star commented on tweets/tests.py
> +        self.assertEqual(Tweet.objects.count(), initial_tweet_count)
５つの修正が完了しました！

2023-11-13 01:56 UTC, sui-false approved these changes

2023-11-13 01:56 UTC, merged